### ISSUE TITLE
input value containing '/' is not substituted as is in the substitution assets

### ISSUE THREAD

**Issue by imajithkv** [aws/codecatalyst-blueprints#289]
Currently when a user passes input variables that are containing `/` and using it in the substitution assets, they get replaced as `&#x2F`.

eg: When I use input such as AWS arn
`arn:aws:iam::xxxxxxxxxx:role/yyyyyyy` it gets replaced as `arn:aws:iam::xxxxxxxxxx:role&#x2Fyyyyyyy` in the substitution asset

Steps To reproduce:
1. Create a project using blueprint builder from CodeCatalyst
2. Update the Options in the `blueprint.ts` to allow input from user
3. Use the input variable to replace the input token using the substitution asset API
4. Synthesize and publish the blueprint preview 
5. Create a new project using the preview with any valid input value containing `/`

Expected:
Input value:`arn:aws:iam::xxxxxxxxxx:role/yyyyyyy` should get substituted as is provided by the user

Actual:
Input value is getting substituted as `arn:aws:iam::xxxxxxxxxx:role&#x2Fyyyyyyy`

Repository to reproduce this issue:
https://ajithkv@git.gamma.source.caws.dev-tools.aws.dev/v1/yellowstone-team/HoneycodePublicAPIIntegration/honeycode-public-api-integration

**Comment by skeppeler** [comment]
[Mustache templating rules](https://github.com/janl/mustache.js?tab=readme-ov-file#variables) are used here so in order to not have the templating engine HTML-escape the variable you would need to use a triple bracket, i.e. `{{{name}}}`. We will update the documentation to make this clear.
