### ISSUE TITLE
SubstitionAsset subsitite method name typo

### ISSUE THREAD

**Issue by schadem** [aws/codecatalyst-blueprints#294]
[https://github.com/aws/caws-blueprints/blob/8a58aa6e1e6152d42d9ceb65f1f2042ae5de33[…]ckages/components/caws-source-repositories/src/static-assets.ts](https://github.com/aws/caws-blueprints/blob/8a58aa6e1e6152d42d9ceb65f1f2042ae5de33cc/packages/components/caws-source-repositories/src/static-assets.ts#L49)

```subsitite(subsitution: any): string {```

guess that should be

```substitute(substitution: any): string{```

**Comment by dsturnbull** [comment]
This is partially addressed. There are many different spellings. 

subsitution substition substitite substitute substitution

Notably, the class itself `SubstitionAsset`.
