### ISSUE TITLE
Support Multi-Select component for Wizard UI

### ISSUE THREAD

**Issue by agdimech** [aws/codecatalyst-blueprints#461]
## Describe your feature request

Having the ability to support a multi-select component with arbitrary content would be super useful.

## Describe the solution you'd like

A new `MultiSelect<T>` component which will render a multi-select ui widget capturing user data based on the schema provided (T). Furthermore, in-built functionality for 'special' types of T should also be supported.

A good example here are BlueprintInstantiations. Ideally i'd love to be able to define something like:

```
export interface Options extends BlueprintOptions {
    readonly blueprints: MultiSelect<BlueprintInstantiation>;
}
```

This would render a multi-select in the UI with a list of all blueprint instantiations within the current Project context.

## Describe alternatives you've considered

N/A.

## Additional context

Having the ability to select multiple blueprint instantations (along with other arbitrary objects) is needed for my particular use-case as my blueprints are designed to interlock with other blueprints.

**Comment by alexforsyth** [comment]
interesting! Looks like we're working on something similar here 
https://github.com/aws/codecatalyst-blueprints/pull/457

Multiselect is currently slated to support repos. We should be able to add 'BlueprintInstantiation' pretty easily

**Comment by agdimech** [comment]
Nice! Just linked this issue to the open PR (added minor comment).
