### ISSUE TITLE
SourceRepository.copyStaticFiles() removes dots ('.') from filenames

### ISSUE THREAD

**Issue by gchagnon** [aws/codecatalyst-blueprints#474]
## Describe the bug

Any files that are copied from static-assets via SourceRepository.copyStaticFiles() get the '.' characters stripped out of their filename. For example, `build.gradle` becomes `buildgradle`.

### My code:
```
const repository = new SourceRepository(this, { title: options_.capabilityName });
repository.copyStaticFiles({
  substitute: {
    capabilityName: options_.capabilityName,
    serviceName: options_.capabilityName.charAt(0).toUpperCase() + options_.capabilityName.slice(1) + 'Service',
    moduleDescription: options_.capabilityDescription,
    industry: options_.industry.toLowerCase(),
    capability: options_.capabilityName.toLowerCase(),
  },
},
    );
```

## Steps to reproduce

1. Create a blueprint that has a file in static-assets with a string substitution in it, e.g. {{productName}}.
2. Use the following to create a repo and substitute productName:
```
const repository = new SourceRepository(this, { title: 'code' });
    repository.copyStaticFiles({
      substitute: {
        productName: 'test'
      },
    },
    );
```

Create a new project from this blueprint.

## Expected / Actual Behavior
Expected: File names are preserved
Actual: '.' chars are stripped

## Version information

- OS: macOS 14.2.1
- Node.js version: 21.1.0

## Additional context

See screenshot
![image](https://github.com/aws/codecatalyst-blueprints/assets/26010814/f4c3709c-fcff-4c08-a3f7-02c03e4674d6)

**Comment by alexforsyth** [comment]
Nice catch! We'll investigate

**Comment by aggagen** [comment]
We released a fix to properly handle file names with `.`s in version `0.3.55` of `@amazon-codecatalyst/blueprint-component.source-repositories`. Thanks for the bug report!
