### ISSUE TITLE
Intermittent errors when applying a blueprint to a project

### ISSUE THREAD

**Issue by gchagnon** [aws/codecatalyst-blueprints#484]
## Describe the bug
When applying a space blueprint to a project I get the following errors repeatedly. I've tried relogging in, refreshing the page, applying the template again, going to the code catalyst home page. 

Error
Error retrieving folder.

Error synthesizing project
session not found

## Steps to reproduce

Intermittent, but when it happens it happens repeatedly. Create a custom blueprint. Apply the blueprint to a project.

<img width="1427" alt="image" src="https://github.com/aws/codecatalyst-blueprints/assets/26010814/45a276b5-2a9e-4ee6-b4d4-d26b5d396182">

**Comment by skeppeler** [comment]
This is an issue with the underlying infrastructure and nothing that can be fixed in this package. Closing this as we're tracking this internally.
