### ISSUE TITLE
Apply blueprint screen shouldn't ask you to downgrade a project or repo created from a newer version of the blueprint

### ISSUE THREAD

**Issue by gchagnon** [aws/codecatalyst-blueprints#485]
## Describe the bug

When applying a blueprint to a project, if a newer unpublished blueprint version is already applied, the screen will say that you have an older version of the blueprint available. This leads to confusion. 

## Steps to reproduce

- Create a custom blueprint, publish version 0.0.1 to the catalog
- Modify the blueprint, do not publish 0.0.2
- Create a project from 0.0.2
- View blueprints tab for the project

## Additional context

![image](https://github.com/aws/codecatalyst-blueprints/assets/26010814/0e254290-de28-4d14-8859-57003690231b)

**Comment by Lock128** [comment]
I guess this is a UI bug and not a blueprints bug and thus not part of this open source repository....?

**Comment by eckertja** [comment]
Will bring this to @nadeempat.

**Comment by avi-alpert** [comment]
Pushing copy updates
