### ISSUE TITLE
GenAI project blue print workflow fails on "default" Compute Runner

### ISSUE THREAD

**Issue by Lock128** [aws/codecatalyst-blueprints#501]
## Describe the bug

When using the [GenAI Project Blueprint](https://github.com/aws/codecatalyst-blueprints/tree/main/packages/blueprints/gen-ai-chatbot) the initial workflow fails as it uses the "default" compute so it gets a "no space left on device".

```Error processing tar file(exit status 1): write /usr/local/lib/python3.11/site-packages/triton/third_party/cuda/bin/ptxas: no space left on device
BedrockChatBotStack-3yxu3v67:  fail: docker build --tag cdkasset-bb7f020b2a9eddb62bb7c3136884815ff5159f2f2c3dbd2ca1139dbb63f4273d --file embedding.Dockerfile --platform linux/amd64 . exited with error code 1: DEPRECATED: The legacy builder is deprecated and will be removed in a future release.
Install the buildx component to build images with BuildKit:
https://docs.docker.com/go/buildx/```

## Steps to reproduce

Steps to reproduce the behavior:

1. Create a new project using the GenAI Blueprint on a CodeCatalyst space with the Free Tier
2. Wait for the workflow to fail


## Expected behavior

The workflow should work...OR...
- add pre-requisites to be non "not-free-tier" AWS account and add a selection option for the Compute Instance to be used by the workflow

## Version information

Blue Print version 0.3.69

**Comment by Lock128** [comment]
Space-ID: 13dcf089-b721-484e-878c-637fe7e365ca
Project-ID in CodeCatalyst: 5788da79-1534-47cb-9811-aad514c0c0e0

**Comment by Lock128** [comment]
After executing the same workflow once again on the free tier it worked succcesfully.... :(

**Comment by skeppeler** [comment]
I have a feeling this was a transient issue with the workflow action, given that it succeeded the second time you executed it. I tried to deploy the blueprint using the same setup as you (space in a free tier) and everything deployed as expected. Do you happen to have the workflow run ID from the failure? I can pass it over to that team to see if they can help debug the failure.

**Comment by Lock128** [comment]
Maybe. Here you have workflow ID and run ID.

workflows/326697c2-8df7-4255-a114-ecf02afaca3a/runs/7522795d-2e2c-41b4-ac9e-e33db284d512

**Comment by skeppeler** [comment]
Thanks. The default compute fleet used is Linux.x86-64.Large and that provides 64GB of disk space - the containers we build along with the source code is well under this limit. The default compute being used is also the same no matter what tier the space belongs to.

I opened a ticket with our workflow team to help triage this further.

**Comment by skeppeler** [comment]
Published an update to the blueprint to use a build image that provides more disk space, per the guidance of our workflows team.
