### ISSUE TITLE
Trying to understand the tokenizer

### ISSUE THREAD

**Issue by jvjfranca** [aws/codecatalyst-blueprints#529]
Hi!

Could you guys please explain why you are using this tokenizer function? I didn't catch how this works.

https://github.com/aws/codecatalyst-blueprints/blob/b56f0f0f64962a109ef54282fc1ea3226073f8d0/packages/blueprints/gen-ai-chatbot/static-assets/chatbot-genai-components/backend/python/embedding/main.py#L112

Thanks in advance,

Best regards.

**Comment by skeppeler** [comment]
This blueprint is ported over from a sample developed by a few AWS prototyping engineers. It might be best to pose that question over in that repository - https://github.com/aws-samples/bedrock-claude-chat/tree/main

This particular line in question was added by [this pull request](https://github.com/aws-samples/bedrock-claude-chat/pull/103).
